export default {
  RECEIVE_USER_DETAILS_FAILURE: 'RECEIVE_USER_DETAILS_FAILURE',
  REQUEST_USER_DETAILS: 'REQUEST_USER_DETAILS',
  FETCH_USER_RESPONSE: 'FETCH_USER_RESPONSE',

  RECEIVE_REPO_FAILURE: 'RECEIVE_REPO_FAILURE',
  REQUEST_REPOS: 'REQUEST_REPOS',
  FETCH_REPOS_RESPONSE: 'FETCH_REPOS_RESPONSE',
  ADD_REPO_FAILURE: 'ADD_REPO_FAILURE',

  REQUEST_USER_REPOS: 'REQUEST_USER_REPOS',
  FETCH_USER_REPO_RESPONSE: 'FETCH_USER_REPO_RESPONSE'
};