export default {
  RECEIVE_USER_DETAILS_FAILURE: 'RECEIVE_USER_DETAILS_FAILURE',
  REQUEST_USER_DETAILS: 'REQUEST_USER_DETAILS',
  FETCH_USER_RESPONSE: 'FETCH_USER_RESPONSE',

  RECEIVE_REPO_FAILURE: 'RECEIVE_REPO_FAILURE',
  REQUEST_PERSONAL_REPOS: 'REQUEST_PERSONAL_REPOS',
  REQUEST_ORG_REPOS: 'REQUEST_ORG_REPOS',
  FETCH_PERSONAL_REPOS_RESPONSE: 'FETCH_PERSONAL_REPOS_RESPONSE',
  FETCH_ORG_REPOS_RESPONSE: 'FETCH_ORG_REPOS_RESPONSE',
  ADD_REPO_FAILURE: 'ADD_REPO_FAILURE',

  REQUEST_WATCHED_REPOS: 'REQUEST_WATCHED_REPOS',
  FETCH_WATCHED_REPO_RESPONSE: 'FETCH_WATCHED_REPO_RESPONSE',

  START_REPORT_BUILD: 'START_REPORT_BUILD',
  FETCH_PRs_RESPONSE: 'FETCH_PRs_RESPONSE',
  FETCH_PRs_FAILURE: 'FETCH_PRs_FAILURE',

  REPORT_SENT_FAILURE: 'REPORT_SENT_FAILURE',
  REPORT_SENT_SUCCESS: 'REPORT_SENT_SUCCESS',

  FETCH_USER_EMAILS_REQUEST: 'FETCH_USER_EMAILS_REQUEST',
  FETCH_USER_EMAILS_RESPONSE: 'FETCH_USER_EMAILS_RESPONSE',
  FETCH_USER_EMAILS_FAILURE: 'FETCH_USER_EMAILS_FAILURE'
};